// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYrH2PFxZ2-5DncAlMTk-DTPRUOnyR5FQ',
    appId: '1:976691170658:web:daae163fbf11924001303b',
    messagingSenderId: '976691170658',
    projectId: 'flutter-firebase-demo-e4c06',
    authDomain: 'flutter-firebase-demo-e4c06.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-e4c06.firebasestorage.app',
    measurementId: 'G-9DF5C71NEW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qyvMkfsgtLjGKzxIwmcXDaBqVz6n5C4',
    appId: '1:976691170658:ios:83a504e7754a1a8301303b',
    messagingSenderId: '976691170658',
    projectId: 'flutter-firebase-demo-e4c06',
    storageBucket: 'flutter-firebase-demo-e4c06.firebasestorage.app',
    iosBundleId: 'com.example.flutterFundamentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qyvMkfsgtLjGKzxIwmcXDaBqVz6n5C4',
    appId: '1:976691170658:ios:83a504e7754a1a8301303b',
    messagingSenderId: '976691170658',
    projectId: 'flutter-firebase-demo-e4c06',
    storageBucket: 'flutter-firebase-demo-e4c06.firebasestorage.app',
    iosBundleId: 'com.example.flutterFundamentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYrH2PFxZ2-5DncAlMTk-DTPRUOnyR5FQ',
    appId: '1:976691170658:web:c2040e74b892f27801303b',
    messagingSenderId: '976691170658',
    projectId: 'flutter-firebase-demo-e4c06',
    authDomain: 'flutter-firebase-demo-e4c06.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-e4c06.firebasestorage.app',
    measurementId: 'G-76RM1V80VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgTdZeAfUIlxREUlR31BwLUYjumRKbjQ',
    appId: '1:976691170658:android:d9a90fccb1ec956f01303b',
    messagingSenderId: '976691170658',
    projectId: 'flutter-firebase-demo-e4c06',
    storageBucket: 'flutter-firebase-demo-e4c06.firebasestorage.app',
  );

}